# numpy는 이제 헷갈리지 말자

- https://sonsh0824.tistory.com/entry/NumPy-Tutorial
- http://taewan.kim/post/numpy_cheat_sheet/
- http://aikorea.org/cs231n/python-numpy-tutorial/#numpy
- http://pythonstudy.xyz/python/article/402-numpy-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0
- https://datascienceschool.net/view-notebook/17608f897087478bbeac096438c716f6/

- 넘파이 데이터
- 넘파이 선언
- 넘파이 나누기
- 넘파이 합성
- Indexing, Slicing and Iterating

- 넘파이 배열 연산(add, multiply, ...)
- sum min cumsum
- 넘파이 Universal Functions - sin, cos, exp, sqrt
- np.random.randint(0, 10, (2, 3))
- np.random.random, np.random.normal, np.random.randn


- 넘파이로 그래프 그리기
- matplotlib
- figure
- plot, hist, scatter, meshgrid
- 그래프 옵션들.
- 그래프 범위
- 그래프 크기
- 서브 플롯

## 넘파이 임포트하기

In [1]:
import numpy as np

## 넘파이 버전 확인

In [2]:
np.__version__

'1.16.4'

## 넘파이의 특징

파이썬 기반 데이터 분석 환경에서 NumPy1는 행렬 연산을 위한 핵심 라이브러리입니다. NumPy는 “Numerical Python“의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공합니다. 특히 메모리 버퍼에 배열 데이터를 저장하고 처리하는 효율적인 인터페이스를 제공합니다. 파이썬 list 객체를 개선한 NumPy의 ndarray 객체를 사용하면 더 많은 데이터를 더 빠르게 처리할 수 있습니다.

NumPy는 다음과 같은 특징을 갖습니다.

- 강력한 N 차원 배열 객체
- 정교한 브로드케스팅(Broadcast) 기능
- C/C ++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

Shape
dtype
dimenstion
rank

---

## **Shape**

넘파이는 다차원 배열을 지원한다. 넘파이 배열의 구조를 Shape으로 표현한다. Shape는 파이썬 튜플 자료형을 활용해서 정의한다.
Shape는 넘파이 배열을 다루는데 계속 사용되므로 정확하게 알고 있어야 한다.

\[1, 2, 4\]  
    Shape : (3,)


\[\[1. 2. 3.\] \[4. 5. 6.\]\]  
    Shape : (2,3)

여기서 \[1. 2. 3.\]는 벡터 처럼 볼수 있다? 

2차원 배열은 (column)(row)순서대로 쓴다?

차원에는 겉에서 봤을때 보이는 덩어리 갯수부터 앞에서 쓴다.

## **numpy array 정보 확인하기**
차원은 dimention이라고 한다.  
dtype은 배열을 구성하는 데이터의 type을 의미한다.

- 타입 확인 : `type(np_arr)`
- shape 확인 : `np_arr.shape`
- dimention 확인 : `np_arr.ndim`
- dtype 확인 : `np_arr.dtype`


In [41]:
import numpy as np

arr = np.array([(1,2,3), (4,5,6)])

print(arr)
print(type(arr))
print("shape", arr.shape)
print("ndim", arr.ndim)
print("dtype", arr.dtype)
print("size", arr.size)
print("itemsize", arr.itemsize)
print("data", arr.data)
print("\n")



arr2 = np.array([(1,2), (4,5), (6, 7)])
print(arr2)
print(type(arr2))
print("shape", arr2.shape)
print("ndim", arr2.ndim)
print("dtype", arr2.dtype)
print("size", arr2.size)
print("itemsize", arr2.itemsize)
print("data", arr2.data)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
shape (2, 3)
ndim 2
dtype int64
size 6
itemsize 8
data <memory at 0x11c9353a8>


[[1 2]
 [4 5]
 [6 7]]
<class 'numpy.ndarray'>
shape (3, 2)
ndim 2
dtype int64
size 6
itemsize 8
data <memory at 0x11c9353a8>


In [2]:
import numpy as np

def pprint(arr):
    print("type: {}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)
    print('\n')

In [16]:
#pprint example

list1 = [1, 2, 4]
np_array1 = np.array(list1)

list2 = [(1,2,3), (4,5,6)]
np_array2 = np.array(list2, dtype = float)

list3 = np.array([[[1,2,3], [4,5,6]], [[3,2,1], [4,5,6]]], dtype = float)
np_array3 = np.array(list3, dtype = float)

pprint(np_array1)
pprint(np_array2)
pprint(np_array3)

type: <class 'numpy.ndarray'>
shape: (3,), dimension: 1, dtype:int64
Array's Data:
 [1 2 4]


type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:float64
Array's Data:
 [[1. 2. 3.]
 [4. 5. 6.]]


type: <class 'numpy.ndarray'>
shape: (2, 2, 3), dimension: 3, dtype:float64
Array's Data:
 [[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]




---
# 배열 생성 및 초기화
Numpy는 원하는 shape으로 배열을 설정하고, 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수를 제공합니다. 또한, 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공합니다. 이 함수를 이용하여 배열 생성하고 초기화할 수 있습니다.

기본 생성방법.  
: np.array(리스트)

원하는 shape으로 배열을 설정하고, 각 요소를 특정 값으로 초기화  
: zeros, ones, full, eye
- **np.zeros(shape, dtype=float, order='C')**  모든 값이 0인 행렬 생성.
- **np.ones(shape, dtype=float, order='C')**  모든 값이 1 인 행렬 생성.
- **np.full(shape, fill_value, dtype=None, order='C')** 모든 값을 지정한 값(fill_value)으로 채운 행렬 생성.



입력한 배열의 shape와 같은 shape의 배열  
: zeros_like, ones_like, full_like

## np.zeros( ), np.ones( )

In [22]:
a = np.zeros((3, 4)) # 모든 값이 0인 행렬 생성.
pprint(a)

b = np.ones((2,3)) #모든 값이 1 인 행렬 생성.
pprint(b)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype:float64
Array's Data:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:float64
Array's Data:
 [[1. 1. 1.]
 [1. 1. 1.]]




## np.empty( ), np.eye( ), np.full( )
 np.eye(N, M=None, k=0, dtype=<class 'float'>)
 (N, N) shape의 단위 행렬(Unit Matrix)을 생성

In [4]:
# np.empty((4,2))
# 초기화 하지 않고, 원래 메모리에 있던 값을 그대로 사용해서 생성.
pprint(np.empty((4,2)))

# np.eye(4)
# 단위행렬로 초기화. 반드시 정사각행렬임.
pprint(np.eye(4))

# np.full((2,2), 7)
# 값이 7인 (2,2)배열로 초기화
a = np.full((2,2),7)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (4, 2), dimension: 2, dtype:float64
Array's Data:
 [[-1.72723371e-077 -1.72723371e-077]
 [ 3.95252517e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000]]


type: <class 'numpy.ndarray'>
shape: (4, 4), dimension: 2, dtype:float64
Array's Data:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


type: <class 'numpy.ndarray'>
shape: (2, 2), dimension: 2, dtype:int64
Array's Data:
 [[7 7]
 [7 7]]




## np.ones_like()
np.zeros_like, np.ones_like, np.full_like, np.enpty_like도 같은 방식으로 존재한다

In [11]:
a = np.array([[1,2,3], [4,5,6]])

b = np.ones_like(a)
pprint(b)

print(a.shape == b.shape)
print('a:',a.shape, 'b:',b.shape)


type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 1 1]
 [1 1 1]]


True
a: (2, 3) b: (2, 3)


---
# **데이터 생성 함수**
NumPy는 주어진 조건으로 데이터를 생성한 후, 배열을 만드는 데이터 생성 함수를 제공합니다.

- numpy.linspace : 시작, 끝을 기준으로 균등하게 나눈 값을 가진다.(시작/끝 점도 포함한다)
- numpy.arange : 시작점으로 부터 입력한 간격에 따라 값을 n개 가진다.
- numpy.logspace : linspace가 동일한 간격으로 나누었다면, logspace는 log간격으로 나눈것이다.


## numpy.linspace
 - numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
 - start부터 stop의 범위에서 num개를 균일한 간격으로 데이터를 생성하고 배열을 만드는 함수
 - 요소 개수를 기준으로 균등 간격의 배열을 생성

In [51]:
a1 = np.linspace(0, 1, 5)
a2 = np.linspace(0, 10, 11)
a3 = np.linspace(0, 10, 6)

print(a1)
print(a2)
print(a3)

[0.   0.25 0.5  0.75 1.  ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.  2.  4.  6.  8. 10.]


## np.arange
 - numpy.arange([start,] stop[, step,], dtype=None)
 - start부터 stop 미만까지 step 간격으로 데이터 생성한 후 배열을 만듦
 - 범위내에서 간격을 기준 균등 간격의 배열
 - 요소의 객수가 아닌 데이터의 간격을 기준으로 배열 생성

In [56]:
a1 = np.arange(0, 10., 2, np.float) # 0부터 10까지 간격 = 2로 생성.
a2 = np.arange(0, 11., 2, np.float)

pprint(a1)
pprint(a2)

type: <class 'numpy.ndarray'>
shape: (5,), dimension: 1, dtype:float64
Array's Data:
 [0. 2. 4. 6. 8.]


type: <class 'numpy.ndarray'>
shape: (6,), dimension: 1, dtype:float64
Array's Data:
 [ 0.  2.  4.  6.  8. 10.]




## 전치 연산(Transpose)

배열의 T속성으로 구할수 있게됐다. 메서드가 아닌 속성

## 크기변형(Reshape)

- 다차원 배열을 무조건 1차원으로 펼치기 위해서는 flatten 나 ravel 메서드를 사용한다.

In [60]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # 출력 "[[1 2]
            #       [3 4]]"
print(x.T)  # 출력 "[[1 3]
            #       [2 4]]"


# rank 1인 배열을 전치할 경우 아무 일도 일어나지 않습니다:
v = np.array([1,2,3])
print(v )   # 출력 "[1 2 3]"
print(v.T)  # 출력 "[1 2 3]"


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
